export const PowerType = {
  Mana: 0,
  Rage: 1,
  Focus: 2,
  Energy: 3,
  ComboPoints: 4,
  Runes: 5,
  RunicPower: 6,
  SoulShards: 7,
  LunarPower: 8,
  HolyPower: 9,
  AlternatePower: 10,
  Maelstrom: 11,
  Chi: 12,
  Insanity: 13,
  Obsolete: 14,
  Obsolete2: 15,
  ArcaneCharges: 16,
  Fury: 17,
  Pain: 18,
  Essence: 19,
};
